name: "HLF-$(Year:yyyy).$(Month).$(Date:dd)$(Rev:.r)"
# Note: This pipeline is based on documentation in: https://github.com/krypc-code/Hyperledger-Fabric-on-Azure-Kubernetes-Cluster
# This pipeline packages, installs, approves, commits and deploys the various chaincodes.

trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

parameters:
# switches to control deployment environment
- name: deployDev
  displayName: Deploy to Dev
  type: boolean
  default: true


# Switches to control deployment individual chaincodes
- name: deployTestChaincode 
  displayName: '1. Test Chaincode'
  type: boolean
  default: true # this is required to be run everytime you do a change to the chaincode
  
variables:
  # chaincode tooling folder
  hlfTDeployToolingRootFolder: $(Build.SourcesDirectory)/krypc_fork

  ######## shared chaincode settings ########
  chaincodeRootFolder: $(Build.SourcesDirectory)/chaincode
  chaincodeSupportEmail: abcs@microsoft.com
  chaincodeCertificateCountry: AU
  chaincodeCertificateState: VIC
  chaincodeCertificateLocality: Melbourne
  chaincodeCertificateOrganisation: ExampleInc
  chaincodeCertificateName: cc-cert
  chaincodeCertificateKeyName: cc-key   
  adminProfileSecretName: adminProfileSecretName
  chaincodeSecretNamePrefix: ccpre
  
  ######## Individual chaincode settings ########
  ######## Test Chaincode ###########
  testChainCodeFolder: $(Build.SourcesDirectory)/chaincode/TestChaincode
  testChainCodeUniqueName: testchaincode
  testChainCodeUniqueLabel: enterprise_2.0
  testChainCodeComponentName: enterprisecc
  testChainCodeUniqueNamespace: hlfenterprise
  testChainCodePort: 9999
  
stages:
- stage: Dev
  displayName: 'Dev deployment'
  condition: eq('${{ parameters.deployDev }}', 'true')
  variables:
  - group: 'hlfvars' # todo: point to your variable group
  jobs:
    - template: templates/Hlf_complete_template.yaml
      parameters:
        deployEnvironment: Dev # todo: point to your environment
        serviceConnectionName: bcserviceconn # todo: point to your service connection name
        adminProfileKeyVaultServiceConnectionName: bcserviceconn # todo: point to your service connection name (you can use the above if it also has access to the Keyvault that stores admin profile)

        deployResources: false # not done in this pipeline
        createConsortium: false # not done in this pipeline
        createChannelAndJoin: false # not done in this pipeline
        runNpmAudit: false # enable as required

        ######## Individual chaincode settings ########
        deployTestChaincode: ${{ parameters.deployTestChaincode }}

